const laptops = [{
  "model_number": "735732606-3",
  "brand_name": "aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi",
  "price": "$2.33",
  "weight": 9,
  "processor_type": "non sodales sed tincidunt eu felis fusce posuere felis sed",
  "ram_size": 49,
  "number_cpu_cores": 14,
  "harddraive_size": 87,
  "display_size": 21,
  "battery_info": "adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien",
  "os": "ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo",
  "touchscreen": true,
  "camera": false
}, {
  "model_number": "215294520-4",
  "brand_name": "congue eget semper rutrum nulla nunc purus phasellus in felis donec semper",
  "price": "$2.31",
  "weight": 14,
  "processor_type": "placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan",
  "ram_size": 8,
  "number_cpu_cores": 42,
  "harddraive_size": 81,
  "display_size": 10,
  "battery_info": "sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue",
  "os": "nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer",
  "touchscreen": true,
  "camera": false
}, {
  "model_number": "682981842-7",
  "brand_name": "primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse",
  "price": "$1.73",
  "weight": 86,
  "processor_type": "ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis",
  "ram_size": 59,
  "number_cpu_cores": 89,
  "harddraive_size": 61,
  "display_size": 91,
  "battery_info": "id consequat in consequat ut nulla sed accumsan felis ut at",
  "os": "lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis",
  "touchscreen": true,
  "camera": false
}, {
  "model_number": "854418812-5",
  "brand_name": "nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in",
  "price": "$4.90",
  "weight": 41,
  "processor_type": "quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus",
  "ram_size": 18,
  "number_cpu_cores": 52,
  "harddraive_size": 68,
  "display_size": 30,
  "battery_info": "diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra",
  "os": "id turpis integer aliquet massa id lobortis convallis tortor risus",
  "touchscreen": false,
  "camera": false
}, {
  "model_number": "491636028-1",
  "brand_name": "dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut",
  "price": "$1.47",
  "weight": 38,
  "processor_type": "feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium",
  "ram_size": 54,
  "number_cpu_cores": 93,
  "harddraive_size": 87,
  "display_size": 10,
  "battery_info": "sapien non mi integer ac neque duis bibendum morbi non quam nec",
  "os": "phasellus id sapien in sapien iaculis congue vivamus metus arcu",
  "touchscreen": false,
  "camera": true
}, {
  "model_number": "164956025-7",
  "brand_name": "dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et",
  "price": "$5.01",
  "weight": 13,
  "processor_type": "sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci",
  "ram_size": 34,
  "number_cpu_cores": 50,
  "harddraive_size": 51,
  "display_size": 69,
  "battery_info": "volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat",
  "os": "duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo",
  "touchscreen": true,
  "camera": true
}, {
  "model_number": "612485026-5",
  "brand_name": "nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate",
  "price": "$2.06",
  "weight": 66,
  "processor_type": "nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis",
  "ram_size": 77,
  "number_cpu_cores": 75,
  "harddraive_size": 64,
  "display_size": 97,
  "battery_info": "venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue",
  "os": "pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac",
  "touchscreen": true,
  "camera": true
}, {
  "model_number": "535647866-6",
  "brand_name": "ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et",
  "price": "$7.12",
  "weight": 70,
  "processor_type": "nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium",
  "ram_size": 9,
  "number_cpu_cores": 33,
  "harddraive_size": 54,
  "display_size": 3,
  "battery_info": "mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer",
  "os": "lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo",
  "touchscreen": false,
  "camera": true
}, {
  "model_number": "599411929-6",
  "brand_name": "diam id ornare imperdiet sapien urna pretium nisl ut volutpat",
  "price": "$1.62",
  "weight": 94,
  "processor_type": "a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus",
  "ram_size": 88,
  "number_cpu_cores": 89,
  "harddraive_size": 74,
  "display_size": 81,
  "battery_info": "posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in",
  "os": "odio donec vitae nisi nam ultrices libero non mattis pulvinar",
  "touchscreen": false,
  "camera": false
}, {
  "model_number": "920445455-5",
  "brand_name": "donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id",
  "price": "$9.16",
  "weight": 57,
  "processor_type": "mi in porttitor pede justo eu massa donec dapibus duis",
  "ram_size": 66,
  "number_cpu_cores": 45,
  "harddraive_size": 81,
  "display_size": 72,
  "battery_info": "interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis",
  "os": "eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget",
  "touchscreen": false,
  "camera": true
}, {
  "model_number": "681173903-7",
  "brand_name": "duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu",
  "price": "$6.63",
  "weight": 52,
  "processor_type": "et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor",
  "ram_size": 63,
  "number_cpu_cores": 9,
  "harddraive_size": 23,
  "display_size": 64,
  "battery_info": "bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui",
  "os": "lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero",
  "touchscreen": true,
  "camera": true
}, {
  "model_number": "994683406-5",
  "brand_name": "primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam",
  "price": "$6.05",
  "weight": 8,
  "processor_type": "diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam",
  "ram_size": 61,
  "number_cpu_cores": 24,
  "harddraive_size": 12,
  "display_size": 24,
  "battery_info": "venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu",
  "os": "nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem",
  "touchscreen": true,
  "camera": false
}, {
  "model_number": "000205868-5",
  "brand_name": "proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit",
  "price": "$7.40",
  "weight": 74,
  "processor_type": "maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat",
  "ram_size": 43,
  "number_cpu_cores": 59,
  "harddraive_size": 45,
  "display_size": 88,
  "battery_info": "morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla",
  "os": "vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas",
  "touchscreen": false,
  "camera": false
}, {
  "model_number": "354453790-7",
  "brand_name": "pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante",
  "price": "$5.53",
  "weight": 80,
  "processor_type": "in magna bibendum imperdiet nullam orci pede venenatis non sodales",
  "ram_size": 15,
  "number_cpu_cores": 50,
  "harddraive_size": 46,
  "display_size": 27,
  "battery_info": "praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam",
  "os": "in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus",
  "touchscreen": false,
  "camera": true
}, {
  "model_number": "283002538-5",
  "brand_name": "nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus",
  "price": "$0.28",
  "weight": 83,
  "processor_type": "vestibulum sit amet cursus id turpis integer aliquet massa id lobortis",
  "ram_size": 91,
  "number_cpu_cores": 62,
  "harddraive_size": 53,
  "display_size": 66,
  "battery_info": "dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien",
  "os": "posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat",
  "touchscreen": false,
  "camera": true
}]
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Laptop').del()
    .then(function () {
      // Inserts seed entries
      return knex('Laptop').insert(laptops);
    });
};
