const laptops = [{
  "model_number": "658900500-1",
  "brand_name": "ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas",
  "price": "$5.88",
  "weight": 78,
  "processor_type": "amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo",
  "ram_size": 99,
  "number_cpu_cores": 87,
  "harddrive_size": 53,
  "display_size": 67,
  "battery_info": "integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices",
  "os": "elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus",
  "touch_screen": false,
  "camera": true
}, {
  "model_number": "001805306-8",
  "brand_name": "ut odio cras mi pede malesuada in imperdiet et commodo",
  "price": "$5.72",
  "weight": 24,
  "processor_type": "blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla",
  "ram_size": 13,
  "number_cpu_cores": 1,
  "harddrive_size": 36,
  "display_size": 76,
  "battery_info": "eu est congue elementum in hac habitasse platea dictumst morbi vestibulum",
  "os": "ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id",
  "touch_screen": true,
  "camera": false
}, {
  "model_number": "713377713-4",
  "brand_name": "metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in",
  "price": "$0.77",
  "weight": 8,
  "processor_type": "odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet",
  "ram_size": 17,
  "number_cpu_cores": 14,
  "harddrive_size": 38,
  "display_size": 77,
  "battery_info": "vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit",
  "os": "enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque",
  "touch_screen": false,
  "camera": false
}, {
  "model_number": "174958526-X",
  "brand_name": "in congue etiam justo etiam pretium iaculis justo in hac habitasse platea",
  "price": "$2.77",
  "weight": 51,
  "processor_type": "a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices",
  "ram_size": 86,
  "number_cpu_cores": 97,
  "harddrive_size": 69,
  "display_size": 6,
  "battery_info": "est risus auctor sed tristique in tempus sit amet sem fusce",
  "os": "in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa",
  "touch_screen": true,
  "camera": true
}, {
  "model_number": "003852919-X",
  "brand_name": "ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue",
  "price": "$9.99",
  "weight": 88,
  "processor_type": "aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio",
  "ram_size": 85,
  "number_cpu_cores": 60,
  "harddrive_size": 28,
  "display_size": 65,
  "battery_info": "erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis",
  "os": "quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi",
  "touch_screen": true,
  "camera": true
}, {
  "model_number": "247535133-0",
  "brand_name": "dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede",
  "price": "$0.10",
  "weight": 87,
  "processor_type": "ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam",
  "ram_size": 98,
  "number_cpu_cores": 76,
  "harddrive_size": 48,
  "display_size": 38,
  "battery_info": "vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla",
  "os": "cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus",
  "touch_screen": true,
  "camera": false
}, {
  "model_number": "673049164-7",
  "brand_name": "in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus",
  "price": "$5.50",
  "weight": 100,
  "processor_type": "leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero",
  "ram_size": 88,
  "number_cpu_cores": 8,
  "harddrive_size": 79,
  "display_size": 55,
  "battery_info": "fusce congue diam id ornare imperdiet sapien urna pretium nisl ut",
  "os": "diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci",
  "touch_screen": false,
  "camera": true
}, {
  "model_number": "319648931-0",
  "brand_name": "lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed",
  "price": "$1.26",
  "weight": 7,
  "processor_type": "felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc",
  "ram_size": 92,
  "number_cpu_cores": 85,
  "harddrive_size": 98,
  "display_size": 92,
  "battery_info": "porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer",
  "os": "ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam",
  "touch_screen": true,
  "camera": false
}, {
  "model_number": "787557479-X",
  "brand_name": "donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante",
  "price": "$2.89",
  "weight": 5,
  "processor_type": "quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus",
  "ram_size": 63,
  "number_cpu_cores": 41,
  "harddrive_size": 53,
  "display_size": 19,
  "battery_info": "in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id",
  "os": "quis augue luctus tincidunt nulla mollis molestie lorem quisque ut",
  "touch_screen": false,
  "camera": false
}, {
  "model_number": "243112872-5",
  "brand_name": "etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl",
  "price": "$6.52",
  "weight": 24,
  "processor_type": "purus eu magna vulputate luctus cum sociis natoque penatibus et magnis",
  "ram_size": 3,
  "number_cpu_cores": 96,
  "harddrive_size": 79,
  "display_size": 36,
  "battery_info": "vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat",
  "os": "turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris",
  "touch_screen": true,
  "camera": false
}, {
  "model_number": "609788256-4",
  "brand_name": "justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit",
  "price": "$0.55",
  "weight": 21,
  "processor_type": "dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam",
  "ram_size": 21,
  "number_cpu_cores": 87,
  "harddrive_size": 28,
  "display_size": 72,
  "battery_info": "orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices",
  "os": "lobortis sapien sapien non mi integer ac neque duis bibendum",
  "touch_screen": true,
  "camera": false
}, {
  "model_number": "457371664-5",
  "brand_name": "curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem",
  "price": "$9.16",
  "weight": 56,
  "processor_type": "dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices",
  "ram_size": 15,
  "number_cpu_cores": 56,
  "harddrive_size": 99,
  "display_size": 5,
  "battery_info": "ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis",
  "os": "mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante",
  "touch_screen": true,
  "camera": false
}, {
  "model_number": "255003888-6",
  "brand_name": "tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent",
  "price": "$6.81",
  "weight": 91,
  "processor_type": "amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales",
  "ram_size": 42,
  "number_cpu_cores": 63,
  "harddrive_size": 28,
  "display_size": 42,
  "battery_info": "nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus",
  "os": "ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna",
  "touch_screen": false,
  "camera": false
}, {
  "model_number": "885745603-X",
  "brand_name": "sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim",
  "price": "$9.33",
  "weight": 5,
  "processor_type": "leo odio porttitor id consequat in consequat ut nulla sed accumsan felis",
  "ram_size": 40,
  "number_cpu_cores": 65,
  "harddrive_size": 88,
  "display_size": 43,
  "battery_info": "enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac",
  "os": "velit donec diam neque vestibulum eget vulputate ut ultrices vel augue",
  "touch_screen": false,
  "camera": false
}, {
  "model_number": "599109989-8",
  "brand_name": "velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat",
  "price": "$4.58",
  "weight": 57,
  "processor_type": "primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui",
  "ram_size": 81,
  "number_cpu_cores": 40,
  "harddrive_size": 45,
  "display_size": 46,
  "battery_info": "dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit",
  "os": "sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id",
  "touch_screen": true,
  "camera": false
}]
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Laptop').del()
    .then(function () {
      // Inserts seed entries
      return knex('Laptop').insert(laptops);
    });
};
