const tablets = [{
  "model_number": "296354675-0",
  "brand_name": "in magna bibendum",
  "price": 480.97,
  "weight": 496.13,
  "processor_type": "systemic",
  "ram_size": 6801,
  "number_cpu_cores": 15,
  "harddrive_size": 1041,
  "display_size": 25,
  "battery_info": "regional",
  "os": "Graphic Interface",
  "camera_info": "tellus nulla ut",
  "depth": 162,
  "height": 153,
  "width": 52
}, {
  "model_number": "562428802-6",
  "brand_name": "ante ipsum primis",
  "price": 411.69,
  "weight": 290.06,
  "processor_type": "cohesive",
  "ram_size": 8253,
  "number_cpu_cores": 12,
  "harddrive_size": 1109,
  "display_size": 24,
  "battery_info": "dedicated",
  "os": "Extended",
  "camera_info": "nulla ultrices aliquet maecenas",
  "depth": 260,
  "height": 88,
  "width": 238
}, {
  "model_number": "060748637-6",
  "brand_name": "ipsum",
  "price": 447.39,
  "weight": 444.22,
  "processor_type": "tangible",
  "ram_size": 4558,
  "number_cpu_cores": 8,
  "harddrive_size": 760,
  "display_size": 18,
  "battery_info": "impactful",
  "os": "ability",
  "camera_info": "orci pede venenatis non sodales sed",
  "depth": 262,
  "height": 242,
  "width": 153
}, {
  "model_number": "599580440-5",
  "brand_name": "integer tincidunt",
  "price": 370.91,
  "weight": 27.01,
  "processor_type": "incremental",
  "ram_size": 4053,
  "number_cpu_cores": 7,
  "harddrive_size": 1185,
  "display_size": 25,
  "battery_info": "contextually-based",
  "os": "firmware",
  "camera_info": "ac consequat metus sapien ut",
  "depth": 196,
  "height": 208,
  "width": 103
}, {
  "model_number": "661204104-8",
  "brand_name": "vestibulum vestibulum ante",
  "price": 189.18,
  "weight": 31.6,
  "processor_type": "motivating",
  "ram_size": 7825,
  "number_cpu_cores": 8,
  "harddrive_size": 504,
  "display_size": 24,
  "battery_info": "Exclusive",
  "os": "next generation",
  "camera_info": "tempus vel pede morbi",
  "depth": 248,
  "height": 77,
  "width": 62
}, {
  "model_number": "120632174-1",
  "brand_name": "tortor",
  "price": 55.28,
  "weight": 106.36,
  "processor_type": "zero tolerance",
  "ram_size": 5162,
  "number_cpu_cores": 13,
  "harddrive_size": 1043,
  "display_size": 18,
  "battery_info": "Ergonomic",
  "os": "Open-architected",
  "camera_info": "nulla nunc purus phasellus in felis",
  "depth": 64,
  "height": 218,
  "width": 97
}, {
  "model_number": "327233893-4",
  "brand_name": "orci",
  "price": 336.57,
  "weight": 38.89,
  "processor_type": "scalable",
  "ram_size": 9440,
  "number_cpu_cores": 11,
  "harddrive_size": 1817,
  "display_size": 23,
  "battery_info": "Triple-buffered",
  "os": "Enhanced",
  "camera_info": "dui luctus rutrum nulla tellus",
  "depth": 148,
  "height": 59,
  "width": 254
}, {
  "model_number": "862553787-1",
  "brand_name": "nec condimentum neque",
  "price": 449.34,
  "weight": 179.2,
  "processor_type": "implementation",
  "ram_size": 3138,
  "number_cpu_cores": 5,
  "harddrive_size": 1524,
  "display_size": 17,
  "battery_info": "3rd generation",
  "os": "synergy",
  "camera_info": "penatibus et magnis dis parturient",
  "depth": 161,
  "height": 66,
  "width": 135
}, {
  "model_number": "426241191-5",
  "brand_name": "fusce consequat",
  "price": 398.27,
  "weight": 270.86,
  "processor_type": "budgetary management",
  "ram_size": 6261,
  "number_cpu_cores": 12,
  "harddrive_size": 1686,
  "display_size": 19,
  "battery_info": "methodology",
  "os": "hybrid",
  "camera_info": "in tempor turpis nec euismod scelerisque quam",
  "depth": 167,
  "height": 122,
  "width": 230
}, {
  "model_number": "383458150-X",
  "brand_name": "venenatis tristique fusce",
  "price": 428.08,
  "weight": 84.61,
  "processor_type": "client-driven",
  "ram_size": 4242,
  "number_cpu_cores": 13,
  "harddrive_size": 1239,
  "display_size": 25,
  "battery_info": "circuit",
  "os": "optimizing",
  "camera_info": "felis eu sapien cursus vestibulum",
  "depth": 270,
  "height": 217,
  "width": 222
}]


exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Tablet').del()
    .then(function () {
      // Inserts seed entries
      return knex('Tablet').insert(tablets);
    });
};
