const users = [
  {
    'first_name': 'Admin',
    'last_name': 'Admin',
    'email': 'admin@admin.com',
    'full_address': '123 Main Street',
    'is_admin': true,
    'phone_number': '1234567890',
    'password': '123',
  }
  /*{
  'first_name': 'Giavani',
  'last_name': 'Linfitt',
  'email': 'glinfitt0@ihg.com',
  'full_address': '5242 Garrison Alley',
  'is_admin': true,
  'phone_number': '3748058897',
  'password': 'password',
}, {
  'first_name': 'Wolfie',
  'last_name': 'Gowen',
  'email': 'wgowen1@delicious.com',
  'full_address': '8755 Amoth Terrace',
  'is_admin': true,
  'phone_number': '8247118396',
  'password': 'password',
}, {
  'first_name': 'Deirdre',
  'last_name': 'Lamke',
  'email': 'dlamke2@mysql.com',
  'full_address': '602 Oriole Trail',
  'is_admin': true,
  'phone_number': '6067550725',
  'password': 'password',
}, {
  'first_name': 'Janessa',
  'last_name': 'Fitzroy',
  'email': 'jfitzroy3@shinystat.com',
  'full_address': '91471 Continental Road',
  'is_admin': false,
  'phone_number': '6585882736',
  'password': 'password',
}, {
  'first_name': 'Rosalynd',
  'last_name': 'Rickell',
  'email': 'rrickell4@purevolume.com',
  'full_address': '768 Schurz Court',
  'is_admin': false,
  'phone_number': '7016402061',
  'password': 'password',
}, {
  'first_name': 'Dallas',
  'last_name': 'Matysiak',
  'email': 'dmatysiak5@wufoo.com',
  'full_address': '4542 Vermont Park',
  'is_admin': false,
  'phone_number': '8757111840',
  'password': 'password',
}, {
  'first_name': 'Minni',
  'last_name': 'Soutar',
  'email': 'msoutar6@yellowpages.com',
  'full_address': '94 Monica Lane',
  'is_admin': false,
  'phone_number': '4716172858',
  'password': 'password',
}, {
  'first_name': 'Wallie',
  'last_name': 'Ghelerdini',
  'email': 'wghelerdini7@storify.com',
  'full_address': '5306 Cambridge Circle',
  'is_admin': true,
  'phone_number': '4985771015',
  'password': 'password',
}, {
  'first_name': 'Selma',
  'last_name': 'MacCostye',
  'email': 'smaccostye8@cisco.com',
  'full_address': '88494 Harbort Avenue',
  'is_admin': false,
  'phone_number': '5835445470',
  'password': 'password',
}, {
  'first_name': 'Rubia',
  'last_name': 'Doble',
  'email': 'rdoble9@seattletimes.com',
  'full_address': '2 Katie Circle',
  'is_admin': false,
  'phone_number': '7403276817',
  'password': 'password',
}, {
  'first_name': 'Bess',
  'last_name': 'Tudhope',
  'email': 'btudhopea@artisteer.com',
  'full_address': '50883 Carpenter Court',
  'is_admin': true,
  'phone_number': '4312490973',
  'password': 'password',
}, {
  'first_name': 'Harri',
  'last_name': 'Tofts',
  'email': 'htoftsb@ca.gov',
  'full_address': '9 Petterle Trail',
  'is_admin': true,
  'phone_number': '4688122530',
  'password': 'password',
}, {
  'first_name': 'Manolo',
  'last_name': 'Kyd',
  'email': 'mkydc@cloudflare.com',
  'full_address': '3 Shasta Lane',
  'is_admin': true,
  'phone_number': '8845403606',
  'password': 'password',
}, {
  'first_name': 'Izaak',
  'last_name': 'Munt',
  'email': 'imuntd@baidu.com',
  'full_address': '7 Loeprich Way',
  'is_admin': true,
  'phone_number': '4314203600',
  'password': 'password',
}, {
  'first_name': 'Lemmy',
  'last_name': 'Bedburrow',
  'email': 'lbedburrowe@uol.com.br',
  'full_address': '0 Porter Drive',
  'is_admin': true,
  'phone_number': '8789635399',
  'password': 'password',
}, {
  'first_name': 'Carlotta',
  'last_name': 'Thuillier',
  'email': 'cthuillierf@cloudflare.com',
  'full_address': '20685 Bowman Terrace',
  'is_admin': true,
  'phone_number': '2599287101',
  'password': 'password',
}, {
  'first_name': 'Chiarra',
  'last_name': 'Jutson',
  'email': 'cjutsong@free.fr',
  'full_address': '5 John Wall Lane',
  'is_admin': true,
  'phone_number': '6506716963',
  'password': 'password',
}, {
  'first_name': 'Afton',
  'last_name': 'Carter',
  'email': 'acarterh@clickbank.net',
  'full_address': '4 Stuart Place',
  'is_admin': false,
  'phone_number': '7289129846',
  'password': 'password',
}, {
  'first_name': 'Scotty',
  'last_name': 'Adamiak',
  'email': 'sadamiaki@cbslocal.com',
  'full_address': '48214 Lukken Place',
  'is_admin': true,
  'phone_number': '3025751432',
  'password': 'password',
}, {
  'first_name': 'Alleyn',
  'last_name': 'Mattioni',
  'email': 'amattionij@stanford.edu',
  'full_address': '44828 Meadow Valley Lane',
  'is_admin': true,
  'phone_number': '7568517595',
  'password': 'password',
}, {
  'first_name': 'Cinderella',
  'last_name': 'Bridal',
  'email': 'cbridalk@ow.ly',
  'full_address': '1 Arizona Crossing',
  'is_admin': true,
  'phone_number': '2655545501',
  'password': 'password',
}, {
  'first_name': 'Gladi',
  'last_name': 'Girhard',
  'email': 'ggirhardl@sitemeter.com',
  'full_address': '98 Bellgrove Place',
  'is_admin': false,
  'phone_number': '7443243002',
  'password': 'password',
}, {
  'first_name': 'Zulema',
  'last_name': 'Bausor',
  'email': 'zbausorm@intel.com',
  'full_address': '9 Russell Lane',
  'is_admin': false,
  'phone_number': '1514633610',
  'password': 'password',
}, {
  'first_name': 'Linnie',
  'last_name': 'Gerardot',
  'email': 'lgerardotn@alibaba.com',
  'full_address': '5 Beilfuss Trail',
  'is_admin': true,
  'phone_number': '8599264711',
  'password': 'password',
}, {
  'first_name': 'Reinhard',
  'last_name': 'Benedit',
  'email': 'rbenedito@fema.gov',
  'full_address': '660 Columbus Avenue',
  'is_admin': true,
  'phone_number': '2154652293',
  'password': 'password',
}, {
  'first_name': 'Ronnie',
  'last_name': 'Postins',
  'email': 'rpostinsp@uol.com.br',
  'full_address': '55 Corben Street',
  'is_admin': false,
  'phone_number': '7903294351',
  'password': 'password',
}, {
  'first_name': 'Hana',
  'last_name': 'Hambright',
  'email': 'hhambrightq@forbes.com',
  'full_address': '7 Hooker Plaza',
  'is_admin': true,
  'phone_number': '3165246049',
  'password': 'password',
}, {
  'first_name': 'Curtis',
  'last_name': 'Huygens',
  'email': 'chuygensr@goo.gl',
  'full_address': '59011 Gina Avenue',
  'is_admin': true,
  'phone_number': '8363559517',
  'password': 'password',
}, {
  'first_name': 'Beulah',
  'last_name': 'Side',
  'email': 'bsides@toplist.cz',
  'full_address': '710 Moland Pass',
  'is_admin': false,
  'phone_number': '7913797295',
  'password': 'password',
}, {
  'first_name': 'Casey',
  'last_name': 'Chaperling',
  'email': 'cchaperlingt@sun.com',
  'full_address': '41 Arkansas Junction',
  'is_admin': false,
  'phone_number': '5869943678',
}
*/];


exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('User').del()
    .then(function() {
      // Inserts seed entries
      return knex('User').insert(users);
    });
};
